### ISSUE TITLE
Unable to set `black-translucent`

### ISSUE THREAD

**Issue by ardatan** [GoogleChromeLabs/pwacompat#12]
First of all, thank you for this great plugin. It actually solves the splash screen problem of my PWA.

I have a little issue on iOS.
According to Apple docs, you can set transparent status bar which is not possible with `pwacompat`.
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html
`pwacompat` only sets `black` or `default` according to theme option.

**Comment by samthor** [comment]
Thanks. I think this is tricky because it might overlap folks' content, which is not what they expect, but maybe it makes sense for (at least) fullscreen.

I'll do some testing and do something in the next release 👍

**Comment by tiptronic** [comment]
+1 on this. 

Right now it seems, we can have either get a splash-screen or 'black-translucent' status bar in fullscreen. Especially on the iPhoneX[rs, etc..] it would be nice, if we could have both :) 

Otherwise: Awesome work! Thanks!

**Comment by samthor** [comment]
I've thought about this and come up [with a PR](https://github.com/GoogleChromeLabs/pwacompat/pull/21). Can you take a look? @tiptronic @ardatan

**Comment by samthor** [comment]
Resolved by #21.

**Comment by ardatan** [comment]
Thank you very much!

**Comment by samthor** [comment]
I'll make a release in the next day or so.

**Comment by samthor** [comment]
Sorry for the delay. I've pushed 2.0.8 now which includes this.
