### ISSUE TITLE
IE Pinned Sites

### ISSUE THREAD

**Issue by Malvoz** [GoogleChromeLabs/pwacompat#16]
IEs _pinned sites_ provides similar features to that of a webmanifest which should be considered, specifically [pinned sites metadata](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/samples/gg491732%28v=vs.85%29); including properties such as `msapplication-starturl` (see the [metadata reference](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/dn255024%28v%3dvs.85%29) for an overview of properties).

Here is some more (possibly redundant) information/visuals:
https://blogs.msdn.microsoft.com/jennifer/2011/04/20/ie-pinned-sites-part-1-what-are-pinned-sites/

Pinned Sites is also supported in MS Edge on Windows 10.

Edit: This is already included, closing.

**Comment by Malvoz** [comment]
Reopening because although some of these properties are included for MS Edge, they're not applied to IE (which still has a wider market share).

I have at least one person who agrees with this:
> IE11 Pinned Sites meta tags doesn’t seem to be something the library is doing and that is probably more useful than other meta tags.

but this is coming from a guy who says: 

### &ldquo;[You shouldn’t use Chrome’s PWACompat library in your Progressive Web Apps](https://medium.com/@firt/you-shouldnt-use-chrome-s-pwacompat-library-in-your-progressive-web-apps-6b3496faab62)&rdquo;

😨 😮 😢

**Comment by samthor** [comment]
So this sounds reasonable but currently the code relies (minimally) on `fetch` and `Promise`.

We'd have to change it to use `XMLHttpRequest`, which is probably fine.

**Comment by samthor** [comment]
I've attacked this in [this commit](https://github.com/GoogleChromeLabs/pwacompat/commit/e0040524dc84a00d1f1409a837798aaa79359f69) and will be releasing it soon. Please try it out and provide feedback!
