### ISSUE TITLE
Mistake in the README.

### ISSUE THREAD

**Issue by konojunya** [GoogleChromeLabs/pwacompat#18]
There is a mistake in the `icons` field of the manifest.webmanifest sample in the Web App Manifest field.

expected

```
"icons": [
    {
        "src": "res/icon-128.png",
        "sizes": "128x128"
    }
  ]
```

actual

```
"icons": [
    "src": "res/icon-128.png",
    "sizes": "128x128"
  ]
```

I'm sorry if you do it on purpose.

**Comment by samthor** [comment]
This was a mistake, fixed now. Thanks!
