### ISSUE TITLE
Add UC Browser Support

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/pwacompat#2]
UC Browser has support for many [manifest like attributes](http://www.uc.cn/download/UCBrowser_U3_API.doc)

appmode, fullscreen etc.

**Comment by samthor** [comment]
Basic support [added here](https://github.com/GoogleChromeLabs/pwacompat/commit/0e7e19c561b1f5cd02cebbfe104a5d52e0e6983a).
