### ISSUE TITLE
iOS splash screen title characters limit

### ISSUE THREAD

**Issue by gracefullight** [GoogleChromeLabs/pwacompat#20]
For compatibility with iOS, This logic fills title.
https://github.com/GoogleChromeLabs/pwacompat/blob/master/pwacompat.js#L160-L177

However, there is no word wrap function, so title is truncated.

- How many characters are splash screen title?
- How about adding word wrap function?

https://www.html5canvastutorials.com/tutorials/html5-canvas-wrap-text-tutorial/

I'd like to contribute, but I do not have all of the iPhone devices 😢

**Comment by samthor** [comment]
Word wrapping the title is definitely possibly but I've not had time to solve it yet.

FWIW without wrapping, it seems like a limit of 15-20 characters might be suitable at the default 24px font size (for a 320px iPhone 5s). This might be temporary advice until we can wrap.

**Comment by samthor** [comment]
Fixed (here)[https://github.com/GoogleChromeLabs/pwacompat/commit/1cee78da193e4f50533304266f36816bfe13601c]. It's not perfect—one long string will still overlap the screen. But if it's a few words it'll wrap properly.
