### ISSUE TITLE
caveats?

### ISSUE THREAD

**Issue by tisdall** [GoogleChromeLabs/pwacompat#22]
I'm wondering if there should be a list of short-comings that this library can't handle.  For example, "start_url" won't be used in iOS and it just uses the current URL.  Also, all regular web links in iOS are opened in a new Safari window and the "scope" value is ignored.  (apparently some of these things are fixed in newer version of iOS that support a web manifest, but I'm curious how that handles both a manifest and the meta attributes being set...  unfortunately I have no way of testing it)

**Comment by samthor** [comment]
Thanks, I'll look at this and make it clear in the README.

**Comment by tisdall** [comment]
If I remember correctly, most of the issues I mentioned are iOS 11.2 and earlier as 11.3 started using the Web App Manifest.  Also, you may want to mention and link to https://gist.github.com/kylebarrow/1042026 as a possible "hack" to allow regular web links to not open in a new window, however when I tried it I had issues with it working in all cases.

**Comment by samthor** [comment]
I've added notes on caveats.

by the way, "start_url" should work fine in iOS—as of iOS 11.3, it's actually read and respected from the manifest properly. See [tracking issue](https://github.com/GoogleChromeLabs/pwacompat/issues/23).

**Comment by tisdall** [comment]
@samthor - I really think 'start_url' being ignored should also be included in the README.  It essentially ignores that and uses whatever the current URL is.  

Thanks for including the section, I hope it helps others out!

**Comment by samthor** [comment]
Sure, but it's fixed as of iOS 11.3. So I can include the caveat for users before that version of iOS.

There is also a sort of fix for this, which I used to provide in PWACompat v1, but it was less relevant going forward. You use `localStorage` and `navigator.standalone` to see if you're the first page loaded, and then redirect. I could bring that back, or maybe generate a CE that your page could listen to.
