### ISSUE TITLE
What does ".filter(Boolean);" mean?

### ISSUE THREAD

**Issue by torvow** [GoogleChromeLabs/pwacompat#24]
The safari crushed when last.removeAttribute("sizes"); // smallest is 'default', no sizes needed

117 return push('link', attr);
118 }).filter(Boolean);

![Screen Shot 2019-03-12 at 7 02 37 PM](https://user-images.githubusercontent.com/46104500/54191540-7a3eeb00-44f9-11e9-8042-b8829017e75a.png)

**Comment by samthor** [comment]
The `.filter(Boolean)` just removes values from a list which are "falsey",
like empty strings or null.

What Safari / iOS version is this?

**Comment by torvow** [comment]
main
v2.0.8 PWA-Compact
and polyfill
v1.1.5 url https://github.com/lifaon74/url-polyfill
v0.1.1 xhr https://github.com/LuvDaSun/xhr-polyfill

last.removeAttribute('sizes');  crushed when remove "sizes" attribute on Safari 600.1.4 / iOS Simulator iPhone 5s iOS 8.1 .

fix :0)
```
  // basic feature detection: from IE10+
  // also fallout on 'navigator.standalone', we _are_ an iOS PWA
  // if (!('onload' in XMLHttpRequest.prototype) || navigator.standalone) {
  //   return;
  // }
```

```
      return attr     //return push('link', attr);
    }).filter(Boolean);

    if (appleTouchIcons.length) {
      var last = appleTouchIcons[appleTouchIcons.length - 1];
   delete last.sizes; // smallest is 'default', no sizes needed
                      // last.removeAttribute('sizes');  crushed when remove !sizes! attribute on
                      // Safari 600.1.4 / iOS Simulator iPhone 5s iOS 8.1 
    } // nb. only for iOS, but watch for future CSS rule `@viewport { viewport-fit: cover; }`
    appleTouchIcons = appleTouchIcons.map(function(attr){
      return push('link',attr)
    })
```

**Comment by samthor** [comment]
I've removed the `.removeAttribute('sizes')` call. I'll release a new version soon!
