### ISSUE TITLE
Unexpected token in position 447

### ISSUE THREAD

**Issue by leolux** [GoogleChromeLabs/pwacompat#28]
Chrome devtools prints out a warning from pwacompat version 2.0.8:
```
pwacompat.min.js:1 pwacompat.js error SyntaxError: Unexpected token / in JSON at position 447
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.e.onload (pwacompat.min.js:1)
```

**Comment by samthor** [comment]
Is it possible that the manifest file you are fetching requires cookies or login?

We set the `.useCredentials` property of the XHR like this:

```js
    xhr.withCredentials = (manifestEl.getAttribute('crossorigin') === 'use-credentials');
```

Alternatively, maybe PWACompat's code that tries to resolve the URL of your manifest isn't working properly. Could you check the network tab to see whether it's requesting the file you expect?

**Comment by leolux** [comment]
No cookies or login required for the manifest file. But my path was wrong. After fixing the file path of the manifest file the issue has gone.
