### ISSUE TITLE
Invalid character in IE11

### ISSUE THREAD

**Issue by SpectralG** [GoogleChromeLabs/pwacompat#30]
Running the demo or including pwacompat in a project yields an error with IE11. The error occurs at the following code.

    if (!manifestHref) {
      throw `can't find <link rel="manifest" href=".." />'`;
    }

The backticks are not accepted in IE11.

**Comment by samthor** [comment]
Please don't use `pwacompat.js`, it's the internal source. You should use `pwacompat.min.js` in your code. I've pushed changes to make this clearer.
