### ISSUE TITLE
Serviceworker should be unregistered from android webview chrome version 37.0.3770.67 ~ 37.0.3770.101

### ISSUE THREAD

**Issue by gracefullight** [GoogleChromeLabs/pwacompat#32]
Related Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=977784

In these chrome version webview, serviceworker blocked all network requests.
Could we handle this exceptional case in this library?

**Comment by samthor** [comment]
Sorry, I don't think this sort of "hot patch" makes sense for PWACompat. It's a very specific browser bug that we may not be able to detect or handle.
