### ISSUE TITLE
Prioritize maskable icons for apple-touch-icon

### ISSUE THREAD

**Issue by NotWoods** [GoogleChromeLabs/pwacompat#33]
If an icon has `"purpose": "maskable"`, that indicates it should not be transparent and is suited to be masked to shapes like iOS' rounded squares. 

Some potential behaviour options:
- Include the maskable icons with no priority (current behaviour)
- If a maskable icon is present, discard the non-maskable icons and only use maskable icons for apple-touch-icon
- Rank maskable icons higher somehow (does Safari use the first icon it encounters?)

**Comment by samthor** [comment]
We could probably prefer the maskable icons for generating the `apple-touch-icon` or splash screen. WDYT?

I don't see a huge disadvantage in continuing to check for and add a solid background. The spec says that maskable icons should not be transparent but can't enforce that in any way.

**Comment by NotWoods** [comment]
I agree that its probably fine to keep adding a solid background. It should be simple to process the maskable icons in the exact same way as a standard icon that's a square with no transparent background. I'm happy to send a PR if you like!

**Comment by samthor** [comment]
Sure, if you like! 👍
