### ISSUE TITLE
Is PWACompat recommended for production projects?

### ISSUE THREAD

**Issue by abdonrd** [GoogleChromeLabs/pwacompat#37]
Is PWACompat recommended for production projects?

As I see it in the `GoogleChromeLabs` GitHub organization I'm not sure.

**Comment by samthor** [comment]
As an update (and I'm closing this): we see lots of use now.

[v8.dev](https://github.com/v8/v8.dev/pull/310/files) uses us as a lazy load just for iOS, via unpkg, with no specific version in mind, which is good practice to always get the latest fixes.
