### ISSUE TITLE
Feature request: prevent meta tags from being added if they already exist

### ISSUE THREAD

**Issue by gangsthub** [GoogleChromeLabs/pwacompat#41]
I was [discussing](https://cmty.app/nuxt/pwa-module/issues/c210) with @pi0 to add pwacompat to https://github.com/nuxt-community/pwa-module but we think that it would be ideal if the [`push` method](https://github.com/GoogleChromeLabs/pwacompat/blob/master/src/pwacompat.js#L127-L134) checked first if those nodes already exist, similarly to what the theme color does: https://github.com/GoogleChromeLabs/pwacompat/blob/master/src/pwacompat.js#L211.

If you're ok with that, I could make a PR ;)

**Comment by samthor** [comment]
Sure, if you'd like to help that would be great!

I'd probably add a helper function which checks for, and adds a meta, if it
doesn't exist.

**Comment by gangsthub** [comment]
I finally had some time during the weekend to submit it! ;P #42
