### ISSUE TITLE
<link rel="apple-touch-icon"> is not created and thus also no icon on boot splash

### ISSUE THREAD

**Issue by jnehlmeier** [GoogleChromeLabs/pwacompat#43]
Since the commit that checks for existence of html tags before adding them to the DOM "apple-touch-icon" links won't be created anymore.

The reason is that the code in the push() method https://github.com/GoogleChromeLabs/pwacompat/blob/a6ba5891e4864f292ee5234a89e6e1208e05e5da/src/pwacompat.js#L172-L179 does not check for "rel" attribute but only for "href" and "sizes". However links with href and sizes attributes have already been inserted by pwacompat while iterating the icons array of the manifest file. Because one of these icons will be the apple-touch-icon the above if will always be true.

**Comment by samthor** [comment]
Thank you for the detailed bug report and apologies for the glaring omission. I've pushed #44.

I think I missed this because on my iPad, the "add to home screen" popup still shows an icon even _without_ the 'apple-touch-icon' elements (which actually seems new).

**Comment by samthor** [comment]
I've pushed this to NPM at version 2.0.14.
