### ISSUE TITLE
Splash screen not shown when added on iPad with landscape orientation 

### ISSUE THREAD

**Issue by Oliviero50** [GoogleChromeLabs/pwacompat#45]
When I add my PWA  to home screen on iPad 6 (2048x1536), the splash screen is only shown when I **add it in portrait mode**. (I can close it and then open it **horizontally** with the splash screen being shown without any problem).

However, when I **add** the PWA to home screen when **the iPad is in landscape mode** and open the PWA, the splash screen is not shown (Only a white screen).

I tried to add orientation:"landscape"/"portrait"/"any" to manifest.json and also played with meta tags without any success.
Bug can be reproduced with demo PWA **emojityper.com** and is also present on the newest version 2.0.14.

**Comment by samthor** [comment]
Thanks, I'll take a look. We should generate both [here](https://github.com/GoogleChromeLabs/pwacompat/blob/master/src/pwacompat.js#L380), but I have an idea why it might be broken.

**Comment by Oliviero50** [comment]
Hi, thanks for your quick response.

I looked a bit deeper into that and it became quite clear where the problem is. 
You generate the 2 base64 images. One for the portait mode and one for the landscape mode. 

When I add the PWA to home screen vertically, the generated base64 **vertical** image is in the link with media="(orientation: **portrait**)"  and the base64 **horizontal** image is in the link with media="(orientation: **landscape**)". That is correct.

However, this is not the case when I add the PWA to homescreen in landscape mode. The generated images are correct, but they are in the swapped, meaning  the **vertical image** is in the link with **orientation="landscape"** and the **horizontal image** is in the link with **orientation="portrait"**. This could be the problem, I guess.

I hope this helps :)

**Comment by Oliviero50** [comment]
Hi, me again!
I could fix that by using screen.width and screen.height instead of availWidth and availHeight.
 
![image](https://user-images.githubusercontent.com/17961489/83131917-e5fe7b00-a0e0-11ea-9c83-de3dc4bf2b54.png)

This is because screen.availWidth and availHeight change depending on the screen orientation, while width and height do not. Using availWidth and availHeight, together with the third parameter 'landscape' caused the splashscreens being swapped.

Kind regards,
Oliver

**Comment by samthor** [comment]
Great! If you want to send a PR that would be great or I can make this fix
later.

**Comment by Oliviero50** [comment]
Hello!
please make the fix, if possible.
Thank you very much!

**Comment by samthor** [comment]
Fixed and published as v2.0.15. Thanks for the report. I've tested it on an iPad8,3 here, adding in portrait but opening in landscape (but the splash screen disappears very quickly).

I feel like iOS might have changed here (and this used to work), but who knows.

**Comment by Oliviero50** [comment]
Thank you! Please also update the package.json version to 2.0.15.

**Comment by samthor** [comment]
Cheers, done.

**Comment by Oliviero50** [comment]
Hi, me again.
The **tagged version v2.0.15** still has the old version  **2.0.14** in package.json. Could you please fix the **v2.0.15 tag**, so that the tagged package.json has the correct version.

**Comment by samthor** [comment]
Done.

I occasionally do this out-of-order (on other projects) but I've never had
anyone complain about it, since most people just ingest the NPM published
version. What is your use-case that needs the tag to be correct here?

**Comment by Oliviero50** [comment]
Thanks!
We fork on GitHub all external libraries relevant for our projects. That is performed automatically (using a bash script) on our Jenkins server.
An installed package.json version is read, which is afterwards used to determine the version tag to be forked.
The final check performs comparison between the installed package version and the forked one.
In case of inconsistency the build is marked as failed.
