### ISSUE TITLE
Use the CDN domain cdn.jsdelivr.net instead of unpkg.com ?

### ISSUE THREAD

**Issue by C0nw0nk** [GoogleChromeLabs/pwacompat#51]
Use CDN domain to serve pwacompat.min.js file instead of unpkg for speed.

https://cdn.jsdelivr.net/npm/pwacompat@latest/pwacompat.min.js

OLD :
```
<script async src="https://unpkg.com/pwacompat" crossorigin="anonymous"></script>
```

NEW :
```
<script async src="https://cdn.jsdelivr.net/npm/pwacompat@latest/pwacompat.min.js" crossorigin="anonymous"></script>
```

**Comment by samthor** [comment]
Very unscientifically, using `curl -L` to fetch the file at my house takes this long:

unpkg.com: ~100ms
jsdelivr: ~70ms

So jsdelivr may be faster. However, both are basically equivalent, and I don't think PWACompat needs to load that fast anyway, see the README:

> You should also consider only loading PWACompat after your site is loaded, as adding your site to a homescreen is a pretty rare operation.

I've included _both_ CDN options in the README now.
