### ISSUE TITLE
short_name/name is showing in splash screen

### ISSUE THREAD

**Issue by skomarfaruque** [GoogleChromeLabs/pwacompat#55]
How i can remove short_name/name from splas screen?

**Comment by samthor** [comment]
There's no option. However you could probably set the custom CSS variable to `0px sans-serif` so it won't render at all, see [this part of the README](https://github.com/GoogleChromeLabs/pwacompat#ios).

**Comment by skomarfaruque** [comment]
Thank you so much. It works fine. @samthor
