### ISSUE TITLE
Advertise use of Subresource Integrity attributes

### ISSUE THREAD

**Issue by Krinkle** [GoogleChromeLabs/pwacompat#6]
I noticed the readme advertises use of the RawGit CDN, and with a fixed version (yay). That means it qualifies for SRI attributes. 

See <https://code.jquery.com> for an example.

* <https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity>
* <ttps://www.srihash.org/>

**Comment by samthor** [comment]
Done.
